services:
  docusaurus:
    image: cloudseidoranalytics/portal:06d25118e04dcdfed6ea0b279cf4d5e42236f4cb
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped