services:
  docusaurus:
    image: cloudseidoranalytics/portal:072b8d31d2e186143d2f7a20447c217e94086e5b
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped