services:
  docusaurus:
    image: cloudseidoranalytics/portal:2e08be568fc53afc4d87be60c9b81407b6132213
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped