services:
  docusaurus:
    image: cloudseidoranalytics/portal:bd996c722d748b85c374715a71b0f1e43cf6f891
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped