services:
  docusaurus:
    image: cloudseidoranalytics/portal:9868b2eb7cde83d2814f39cec38c764036d8970b
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped