services:
  docusaurus:
    image: cloudseidoranalytics/portal:7fba60713cf3a47e732c9065440633721c579aad
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped