services:
  docusaurus:
    image: cloudseidoranalytics/portal:014ee08f2957f63f063f18100d87264e28b9f9ad
    # IMPORTANTE: No añadir sección 'build' aquí. 
    # La imagen se construye en GitHub Actions y Portainer solo debe descargarla (PULL).
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped