services:
  docusaurus:
    image: cloudseidoranalytics/portal:bdd8b9d7105de1df4de5d0f8e00f3b69ede31903
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped