services:
  docusaurus:
    image: cloudseidoranalytics/portal:8573b53fa1fb3b2d58c6d7e70a74e356a75454c1
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped