services:
  docusaurus:
    image: cloudseidoranalytics/portal:af5bbe14a145f4b67a25ab828b43dee04a55d315
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped