services:
  docusaurus:
    image: cloudseidoranalytics/portal:b143630d7947251caf7e02ca29d4b9c79c9083a7
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped