services:
  docusaurus:
    image: cloudseidoranalytics/portal:5718b2668a35afa5479e8a577f896ae96a457194
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped