services:
  docusaurus:
    image: cloudseidoranalytics/portal:97f16ead7cd4bba0d13d471a1f3eb28b7626e0b6
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped