services:
  docusaurus:
    image: cloudseidoranalytics/portal:b004887cfab3388646efe1673ce31b4903e1a008
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped