services:
  docusaurus:
    image: cloudseidoranalytics/portal:2656306c232fbac71afa8e607dd6d07aa362d8ad
    # IMPORTANTE: No añadir sección 'build' aquí. 
    # La imagen se construye en GitHub Actions y Portainer solo debe descargarla (PULL).
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped