services:
  docusaurus:
    image: cloudseidoranalytics/portal:d3842c0bdf11102f8896c45e33855a492f3ab05d
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped