services:
  docusaurus:
    image: cloudseidoranalytics/portal:f1d213620ffc8f1f09f27fc35283aeb65a399148
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped