services:
  docusaurus:
    image: cloudseidoranalytics/portal:41e4753113ef5bd8302e2f931c315fa2d086b8c4
    build:
      context: .
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped